import type { Metadata } from "next";
import { Saira, Saira_Condensed } from "next/font/google";

// Components
import Header from "./component/header";
import Footer from "./component/footer";

// Styles
import "./styles/main.scss";

const saira = Saira({
    variable: "--font-saira",
    subsets: ["latin"],
});

const sairaCondensed = Saira_Condensed({
    variable: "--font-saira-condensed",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Tim Schieber | Developer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${saira.variable} ${sairaCondensed.variable}`}
                data-theme="dark">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
